test:
  sessions:
    default:
      database: internal_test
      hosts:
        - localhost:27017
      options:
        read: primary
        max_retries: 1
        retry_interval: 0
  options:
    raise_not_found_error: false
