test:
  sessions:
    default:
      database: internal_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        identity_map_enabled: true
  options:
    raise_not_found_error: false
